print('โปรดกรอกชื่อ')
name = str(input('ชื่อ :'))
print('โปรดกรอกอายุ')
age = int(input('อายุ :'))
print('โปรดกรอกรหัสประจำตัว')
ID = int(input('รหัสประจำตัว :'))
print('โปรดกรอกระดับชั้น')
level = int(input('ระดับชั้น :'))
print('โปรดกรอกชื่อเล่น')
nickname = str(input('ชื่อเล่น :'))
print('โปรดกรอกส่วนสูง')
height = float(input('ส่วนสูง :'))
print('โปรดกรอกน้ำหนัก')
weight = float(input('น้ำหนัก :'))
print(f"ชื่อ : {name} , อายุ : {age} ปี")
print(f"รหัสประจำตัวนักเรียน :{ID} , ระดับชั้น : {level}")
print(f"ชื่อเล่น :{nickname}")
print(f"ส่วนสูง : {height} เซนติเมตร , น้ำหนัก : {weight}กิโลกรัม")
num = height + weight
print("ส่วนสูง + น้ำหนัก =",(num))